import './js/header';
import './js/hero';
import './js/about';
import './js/reviews';
import './js/howtoplay';
import './js/gallery';
import './js/advantages';
import './js/disclaimer';
import './js/footer';
